# © Copyright 2025 Stuart Parmenter
# SPDX-License-Identifier: MIT

# Test configuration for new modular DDP architecture
# Tests: ddp core component + ddp_light_effect renderer (RGB LEDs)

esphome:
  name: ddp-test-light-rgb
  friendly_name: DDP Light RGB Test

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: github://stuartparmenter/ddp-esphome@main
    components: [ddp]
    refresh: 0s

# Core DDP component - handles UDP reception and protocol
ddp:
  id: ddp_server
  port: 4048

# LED strip configuration
light:
  - platform: esp32_rmt_led_strip
    id: led_strip
    rgb_order: GRB
    pin: GPIO5
    num_leds: 256
    rmt_channel: 0
    chipset: WS2812
    name: "LED Strip"
    effects:
      - ddp_light_effect:
          name: "DDP Stream"
          ddp_id: ddp_server
          stream: 1
