# © Copyright 2025 Stuart Parmenter
# SPDX-License-Identifier: MIT

# Test configuration for new modular DDP architecture
# Tests: Multiple renderers - same stream to both canvas AND LEDs

esphome:
  name: ddp-test-multi
  friendly_name: DDP Multi-Renderer Test

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: github://stuartparmenter/ddp-esphome@main
    components: [ddp, ddp_canvas]
    refresh: 0s

# Core DDP component - handles UDP reception and protocol
ddp:
  id: ddp_server
  port: 4048

# Canvas renderer - renders DDP stream to LVGL canvas
ddp_canvas:
  - id: canvas_renderer_1
    ddp_id: ddp_server
    stream: 1              # Stream 1
    canvas: canvas_main
    width: 64
    height: 64
    back_buffers: 2

# LED strip - same stream mirrored to LEDs!
light:
  - platform: esp32_rmt_led_strip
    id: ambient_leds
    rgb_order: GRB
    pin: GPIO5
    num_leds: 64
    rmt_channel: 0
    chipset: WS2812
    name: "Ambient LEDs"
    effects:
      - ddp_light_effect:
          name: "DDP Mirror"
          ddp_id: ddp_server
          stream: 1          # Same stream 1!

# LVGL setup
lvgl:
  displays:
    - display_id: my_display

  pages:
    - id: page_main
      widgets:
        - canvas:
            id: canvas_main
            width: 64
            height: 64
            x: 0
            y: 0

# Display
display:
  - platform: ili9xxx
    id: my_display
    model: ST7789V
    dimensions:
      width: 240
      height: 240
    cs_pin: GPIO10
    dc_pin: GPIO11
    reset_pin: GPIO12
    auto_clear_enabled: false
    update_interval: never
